//
//  NoInternetPresenter.swift
//  FintechBase
//
//  Created by Ranjith Ravichandran on 14/06/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoInternetPresentationLogic {
    func presentSomething(response: NoInternet.Something.Response)
}

class NoInternetPresenter: NoInternetPresentationLogic {
    weak var viewController: NoInternetDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: NoInternet.Something.Response) {
        let viewModel = NoInternet.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
