//
//  NoInternetRouter.swift
//  FintechBase
//
//  Created by Ranjith Ravichandran on 14/06/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NoInternetRoutingLogic {
    // func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol NoInternetDataPassing {
    var dataStore: NoInternetDataStore? { get }
}

class NoInternetRouter: NSObject, NoInternetRoutingLogic, NoInternetDataPassing {
    weak var viewController: NoInternetViewController?
    var dataStore: NoInternetDataStore?
}
