//
//  NoInternetViewController.swift
//  FintechBase
//
//  Created by Ranjith Ravichandran on 14/06/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoInternetDisplayLogic: AnyObject {
    func displaySomething(viewModel: NoInternet.Something.ViewModel)
}

class NoInternetViewController: UIViewController, NoInternetDisplayLogic {
    var interactor: NoInternetBusinessLogic?
    var router: (NSObjectProtocol & NoInternetRoutingLogic & NoInternetDataPassing)?
    @IBOutlet weak var tryAgainButton: UIButton?
    @IBOutlet weak var titleLabel: UILabel?
    @IBOutlet weak var subTitleLbl: UILabel?
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        initializeUI()
    }
    
    // MARK: Do something
    func doSomething() {
        let request = NoInternet.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: NoInternet.Something.ViewModel) {
        // nameTextField.text = viewModel.name
    }
    
    /*Retry action*/
    @IBAction func `tryAgainAction`(_ sender: UIButton) {
        guard isInternetAvailable() else {
            return
        }
    }
}

// MARK: Initial Loads
extension NoInternetViewController {
    
    private func initializeUI() {
        titleLabel?.font = .setCustomFont(name: .semiBold, size: .x18)
        titleLabel?.textColor = .secondaryBlackTextColor
        titleLabel?.text = AppLoacalize.textString.noInternetTitle
        
        subTitleLbl?.font = .setCustomFont(name: .regular, size: .x12)
        subTitleLbl?.textColor = .midGreyColor
        subTitleLbl?.paragraphLineHeight(string: AppLoacalize.textString.noInternetSubTitle, lineHeight: 1.24, alignment: .center)
        
        tryAgainButton?.setup(title: AppLoacalize.textString.tryAgain, type: .primary, isEnabled: true)
    }
}
