//
//  NoInternetInteractor.swift
//  FintechBase
//
//  Created by Ranjith Ravichandran on 14/06/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoInternetBusinessLogic {
    func doSomething(request: NoInternet.Something.Request)
}

protocol NoInternetDataStore {
    // var name: String { get set }
}

class NoInternetInteractor: NoInternetBusinessLogic, NoInternetDataStore {
    var presenter: NoInternetPresentationLogic?
    var worker: NoInternetWorker?
    // var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: NoInternet.Something.Request) {
        worker = NoInternetWorker()
        worker?.doSomeWork()
        
        let response = NoInternet.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
